[versions]
agp = "8.11.1"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
cardview = "1.0.0"
room_version = "2.6.1"
ksp_version = "2.0.21-1.0.25"
gson_version="2.11.0"
retrofit_version="2.11.0"
okHttpClient_version="4.12.0"
viewModel_version="2.8.6"
liveData_version="2.8.6"
lifecycle_version="2.8.6"
reactiveStreams_version="2.8.6"
picasso_version="2.8"
work_manager = "2.9.1"
dagger2_version = "2.52"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
#Библиотека Room
room = {group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
#Кодогенератор
room-compiler = {group="androidx.room", name = "room-compiler", version.ref ="room_version"}
#optional - Kotlin Extensions and Coroutines support for Room
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room_version"}
#Retrofit
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref ="retrofit_version"}
#конвектор gson
gson = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref ="gson_version"}
#Picaso
picasso = {group = "com.squareup.picasso", name = "picasso", version.ref ="picasso_version"}
#WorkManager
work-manager = { group = "androidx.work", name = "work-runtime", version.ref = "work_manager" }
#ViewModel
viewModel = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref ="viewModel_version"}
#LiveData
liveData = {group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref ="liveData_version"}
#Annotation processor
liveDataCompiler = {group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref ="lifecycle_version"}
#optional - ReactiveStreams support for LiveData
reactiveStreams = {group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref ="reactiveStreams_version"}
#OkHttpClient- не обязательна
okHttpClient = {group = "com.squareup.okhttp3", name = "okhttp", version.ref ="okHttpClient_version"}
#HttpLoggingInterceptor- не обязательна
httpLoggingInterceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref ="okHttpClient_version"}
#Dagger2
dagger2 = { group = "com.google.dagger", name = "dagger", version.ref = "dagger2_version" }
#Dagger2 кодогенратор
dagger2-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger2_version" }
#Dagger2 аннотации
dagger2-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger2_version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref ="ksp_version"}

